
import { SectionProvider } from "@/Context/Context";
import "./globals.css";

export const metadata = {
  title: "Ping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-700">
        <SectionProvider>
        {children}
        </SectionProvider>
        </body>
    </html>
  );
}
